version: 2
jobs:
  test-job:
    docker:
      - image: node:12

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: Run test
          command: yarn test

  release-job:
    docker:
      - image: node:12
    steps:
      - checkout
      - run:
          name: set npm config
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn install
      - run: yarn build
      - run:
          name: release to npm
          command: npm publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - test-job:
          filters:
            tags:
              only: /.*/

      - release-job:
          requires:
            - test-job
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
